### ISSUE TITLE
Unclear meaning of DateTime for Gauges

### ISSUE THREAD

**Issue by dv00d00** [justeat/JustEat.StatsD#103]
There are two methods in `StatsDMessageFormatter` class which are using DateTime parameter

``` csharp

public string Gauge(double magnitude, string statBucket, DateTime timestamp)
{
    var stat = string.Format(InvariantCulture, "{0}{1}:{2}|g|@{3}", _prefix, statBucket, magnitude, timestamp.AsUnixTime());
    return Format(DefaultSampleRate, stat);
}

public string Gauge(long magnitude, string statBucket, DateTime timestamp)
{
    var stat = string.Format(InvariantCulture, "{0}{1}:{2}|g|@{3}", _prefix, statBucket, magnitude, timestamp.AsUnixTime());
    return Format(DefaultSampleRate, stat);
}

```

I was not able to find any reference to Unix timestamp in statsd docs

https://github.com/b/statsd_spec#gauges
https://statsd.readthedocs.io/en/v3.3/types.html#gauges
https://github.com/etsy/statsd/blob/master/docs/metric_types.md#gauges

Also this paragraph 

```
The StatsClient.gauge() method also support the rate parameter to sample data back to the statsd server, but use it with care, especially with gauges that may not be updated very often.
```

Am I missing something?

**Comment by slang25** [comment]
Agreed, it looks weird. Can't see any real justification in the (very old) commit that added it: https://github.com/justeat/JustEat.StatsD/commit/63c1a4517ed133cc479465d2d56f097703053ba7

**Comment by martincostello** [comment]
I'd concur that we could drop it as part of `4.0.0`.
