### ISSUE TITLE
StatsDPublisher(StatDConfiguration) creates a resource leak

### ISSUE THREAD

**Issue by martincostello** [justeat/JustEat.StatsD#119]
The `StatsDPublisher(StatsDConfiguration)` constructor creates a resource leak.

https://github.com/justeat/JustEat.StatsD/blob/3ca60f3cdac2d9cfde4f66c73c19de35dd1c8c15/src/JustEat.StatsD/StatsDPublisher.cs#L39-L59

Given that `SocketTransport` implements `IDisposable`, using this constructor will leak sockets beyond the lifetime of the publisher as there is no way to deterministically dispose of the sockets it pools.

This is only really a problem where the publisher isn't a singleton and/or isn't used for the lifetime of the application.

**Comment by AnthonySteele** [comment]
The publisher should be a singleton that lives as long as the app. Or in some apps, there are 2 or 3 differently-configured publishers in use. Performance will be _terrible_ if you make a new publisher each time.

All the same, there should be a way to tear it down. Should `StatsDPublisher` implement `IDisposable` ?

**Comment by martincostello** [comment]
Either we need to make it `IDisposable` (and some other types due to the wrapping so it chains), or we need to remove this constructor.

The removal option is the least-good option to the end-user because it makes the API harder to use as you can't _"just make a publisher"_ anymore and are required to understand more of the way the library works (now you need a transport, and to make a transport you need an endpoint, so you need to find out how to do that).
