### ISSUE TITLE
Rename "IPEndPointSource"?

### ISSUE THREAD

**Issue by martincostello** [justeat/JustEat.StatsD#120]
As part of v4, should be rename `IPEndPointSource`.

Naming conventions imply it's an _interface_ of type _PEndpointSource_.

I don't have a great alternative to hand right now, but it irks me slightly that it doesn't follow conventions, and as we're doing breaking changes right now we're at a point where we can _consider_ changing it.

**Comment by AnthonySteele** [comment]
Maybe `IEndPointSource`, as in "An interface of type _EndpointSource_ "

**Comment by shaynevanasperen** [comment]
Maybe drop the interface altogether and use `Func<IPEndpoint>` in it's place?

**Comment by martincostello** [comment]
Interesting idea.

**Comment by AnthonySteele** [comment]
Fixed by #136
