### ISSUE TITLE
Rename EndpointParser?

### ISSUE THREAD

**Issue by martincostello** [justeat/JustEat.StatsD#154]
I just stumbled across this comment: https://github.com/justeat/JustEat.StatsD/blob/2c989e99cd9cfe0827d147d5b2cbbf9e35d561b0/src/JustEat.StatsD/EndpointLookups/EndpointParser.cs#L6

Should we rename this type as suggested, or just remove the comment?

At a minimum we should probably rename to `EndPointParser` (capital P) if we don't want to make it a _factory_.

**Comment by AnthonySteele** [comment]
My opinions on the naming aren't strong. The parsing happens on line 62: ` if (IPAddress.TryParse(host, out IPAddress address))` and with the various other checks on param values.

I think it's correct that this class is more of a factory or builder of `IEndPointSource` instances than it is a parser (it calls `TryParse` on another class, it does not implement it) and the naming could be changed to match.

**Comment by martincostello** [comment]
I'll do a PR to tweak it shortly then, once I've finished my pass of the docs for #130 that I'm half-way through.
