### ISSUE TITLE
Gauge increment

### ISSUE THREAD

**Issue by bastiflew** [justeat/JustEat.StatsD#175]
### Expected behaviour

Hello, in unit tests related to gauge : https://github.com/justeat/JustEat.StatsD/blob/9e80cf2801b235f057c022664c54feb91622df19/tests/JustEat.StatsD.Tests/Utf8FormatterTests.cs#L52
Is it a test to set the gauge value to 128, or to increment the value by 128 ?
If it should increment, we should have "+128" in the message, and if it's a test for setting the value, how do we increment a gauge ?

### Actual behaviour

Only set the gauge value or decrement (since minus is materialized in the message)

Thanks

**Comment by AnthonySteele** [comment]
As far as I know, we support setting the gauge to a specific value.

[Statsd also allows incrementing or decrementing a gauge by a value](https://github.com/statsd/statsd/blob/master/docs/metric_types.md#gauges). Which is something that we could look at.

**Comment by jcavandoli** [comment]
Hi!
I'm working with @bastiflew and I've updated your library so it support set, increment and decrement for gauge method.
I can send you a pull request soon if you want :)
