### ISSUE TITLE
Add ability to provide CloudWatch custom metrics

### ISSUE THREAD

**Issue by Berezhnyk** [justeat/JustEat.StatsD#198]
### Expected behavior

I would like to provide custom metrics to StatsD so that gives me the ability to use CloudWatch features. 
`MetricName:value|type|@sample_rate|#tag1:
  value,tag1...`

CloudWatch custom metrics doc: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-custom-metrics-statsd.html
### Actual behaviour

MetricName:value|type|@sample_rate

**Comment by Berezhnyk** [comment]
@martincostello I would like to implement it by myself.

**Comment by martincostello** [comment]
Cool - feel free to submit a PR and we can review it 😃
