### ISSUE TITLE
Do we need to have Culture?

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/JustEat.StatsD#56]
Do we need to have a `CultureInfo` object at all?

The `Culture` is on the `StatsDConfiguration` and defaults to `CultureInfo.InvariantCulture`
If you change it, it affects the way that metrics values are formatted for decimals and maybe other things.
But these metrics are not formatted for display, they are formatted to send to a server.

Does a statsd server really need culture-specific formatting? Under what circumstances is it a good idea to change it? If not, let's delete it, and then we can look at removing use of `string.Format` as an optimisation. As long as we format with a user-supplied  `CultureInfo` object, this will be hard to change. And it looks like yet more overdesign.

**Comment by martincostello** [comment]
I'd always wondered why you'd want to do this as well...

**Comment by AnthonySteele** [comment]
So we _usually_  leave the culture as `InvariantCulture`. We know that our stats servers accepts that.
Do our stats servers accept other formats? We don't know, but can find out.
Do other people have stats servers that _require_ other culture settings? We don't know.
[There are some docs here](https://github.com/etsy/statsd/blob/master/docs/metric_types.md) but not much mention of floats or float formats.

**Comment by slang25** [comment]
My bet is it was left in because they may have been unsure when first creating this library. Logically I can't see how it would be valid to use anything other than invariant.

**Comment by AnthonySteele** [comment]
So If I'm sending a stat, e.g an increment, it's a UDP packet containing a line of text like `some.stat.name:1|c`
Can also be a float, I think? `some.stat.name:2.4|c`

The basic question here is, what would happen if [a different culture format](https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html) was applied to that float, e.g. 
`some.stat.name:2,4|c`

**Comment by martincostello** [comment]
Try it with something _really_ different like Japanese etc. where it doesn't even use the same number characters and see what happens. I'm starting to think more and more this is a case of YAGNI.

**Comment by AnthonySteele** [comment]
It was most likely introduced to prevent this code from picking up the server or UI culture format, which could easily be e.g. French or Danish. Making it configurable however looks like YAGNI overengineering, and is now preventing optimisations.

**Comment by slang25** [comment]
I was nosing around other .NET implementations, they use `InvariantCulture` ¯\_(ツ)_/¯

**Comment by martincostello** [comment]
Let's 🗑 it then.

**Comment by justeattech** [comment]
We left it in becuase Resharper told us to...lol

On Wednesday, 25 April 2018, Stuart Lang <notifications@github.com> wrote:

> My bet is it was left in because they may have been unsure when first
> creating this library. Logically I can't see how it would be valid to use
> anything other than invariant.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_justeat_JustEat.StatsD_issues_56-23issuecomment-2D384396188&d=DwMCaQ&c=wk_wm7TP2bO6R6iBMpAOQA&r=fsiXnlr20TgfMb2fnQYjPQ&m=qk52-vbEgP6YAG-gN6Ez2BFZAY-UzMzKHuyhf6guwNY&s=wUtpO7K5_OtGIgU2iB0nFVRfnqrHJTnuBYQTNtWxfwg&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGshPPt11myyUhopDh0O6ti9ujVIHlDFks5tsMZSgaJpZM4TdaVV&d=DwMCaQ&c=wk_wm7TP2bO6R6iBMpAOQA&r=fsiXnlr20TgfMb2fnQYjPQ&m=qk52-vbEgP6YAG-gN6Ez2BFZAY-UzMzKHuyhf6guwNY&s=as0qFBcw9h8TQZaKbmQCnG3N_CLBrcMS-V2IEgCQLRM&e=>
> .
>


-- 

Fleet Place House:

Jaimal Chohan *Principal Engineer in Partner Product Development*

Web  www.just-eat.com

Fleet Place House, 2 Fleet Place, London, EC4M 7RF

-- 



This is an e-mail from the company JUST EAT plc. This e-mail may contain 
confidential information and/or privileged or personal advice. This e-mail 
is intended for the addressee(s) stated above only. If you receive this 
e-mail by mistake, please return it to JUST EAT plc without producing, 
distributing or retaining copies hereof. Thank you.

**Comment by martincostello** [comment]
Resolved by #60.
