### ISSUE TITLE
replace the perf test harness with Benchmark.net

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/JustEat.StatsD#57]
### Expected behaviour

Industry standard perf test harness

### Actual behaviour

A less-functional hand-rolled one.

**Comment by martincostello** [comment]
Unless there's something I missed when I last tried it , BMDN is fine for speed, but wasn't useful for me to look at processor load (the socket pooling thing I was talking about in #55).

**Comment by AnthonySteele** [comment]
Does the existing PerfTestHarness help with processor load?

**Comment by martincostello** [comment]
It was more _seeing_ the processor load, than whether or not it created load.

**Comment by AnthonySteele** [comment]
Done
