### ISSUE TITLE
Make IEndPointSource.GetEndpoint async?

### ISSUE THREAD

**Issue by martincostello** [justeat/JustEat.StatsD#93]
While refactoring some code for #92, I found this:

https://github.com/justeat/JustEat.StatsD/blob/3aa3b83f9334033dc5fcd36dc6367118dd5163a0/src/JustEat.StatsD/EndpointLookups/DnsLookupIpEndpointSource.cs#L27-L28

As part of v4.0.0 when we can make breaking interface changes, we should consider making `GetEndpoint()` async and accept a `CancellationToken`.

Then we can fix `DnsLookupIpEndpointSource` to be properly asynchronous.

For example:

```csharp
using System.Net;
using System.Threading;
using System.Threading.Tasks;

namespace JustEat.StatsD.EndpointLookups
{
    public interface IEndPointSource
    {
        Task<IPEndPoint> GetEndpointAsync(CancellationToken cancellationToken = default);
    }
}
```

**Comment by AnthonySteele** [comment]
The problem is that this one corner case would essentially make the whole call stack async. And then [Simple timers](https://github.com/justeat/JustEat.StatsD#simple-timers) would have to use an async `IDisposable` pattern, which isn't even out yet.
